# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init:  |
      sudo pip3 install streamlit
      sudo apt install -y mosquitto
      sudo apt install mosquitto-clients
      sudo service mosquitto start
      sudo service mosquitto start
      sudo pip3 install paho-mqtt
      git clone https://github.com/eclipse/paho.mqtt.python.git
      cd paho.mqtt.python
      python setup.py install
      cd ..

    command: streamlit run pagina.py

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1883
    onOpen: ignore
    
  - port: 8501
    name: Web App
    description: Computer's Microphone Signal in Real Time
    onOpen: open-browser
    visibility : public
