# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init:  |
      sudo pip3 install streamlit
      streamlit hello
      
      
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8501
    onOpen: open-preview
    visibility : public
