# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init:  |
      sudo pip3 install streamlit
      sudo apt install -y mosquitto
      sudo apt install mosquitto-clients
      sudo service mosquitto start
      sudo systemctl enable mosquitto
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8501
    onOpen: open-browser
    visibility : public
